name: javadoc

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Create javadoc
      run: mvn javadoc:javadoc --file pom.xml
      working-directory: ./app

    - name: Upload an artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: javadocs
        path: ./app/target/site/apidocs/
